FROM quay.io/packit/dist2src:dev

RUN dnf -y install epel-release && dnf -y install mock python3-ogr packit

COPY pkg_survey/survey.py onboard/run-onboard.sh onboard/onboard.py master-branches/* /workdir

CMD bash /workdir/run-onboard.sh
